version: '3.2'
services:
  arangodb:
    container_name: arango-database
    image: arangodb/arangodb:3.7.8
    ports:
      - 8529:8529
    environment:
      ARANGO_ROOT_PASSWORD: "root"
  backend:
    build: backend
    container_name: backend
    command: npm run start
    depends_on:
      - arangodb
    volumes:
      - type: bind
        source: ./backend
        target: /usr/src/app/
    ports:
      - 8080:8080

volumes:
  database:
